graph TD
      a[Apps - Calculation, Graph, etc.] --> b[Escher - GUI Toolkit]
      a --> c[Poincaré - Mathematical engine]
      b --> d[Kandinsky - Graphics Engine]
      d --> e[Ion - Hardware abstraction layer]
      b --> e